# Generated by Django 5.2.11 on 2026-03-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('InProgress', 'In Progress'), ('Resolved', 'Resolved')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
