# Generated by Django 5.2.11 on 2026-03-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_incident_severity_incident_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='location',
        ),
        migrations.AddField(
            model_name='incident',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
